### ISSUE TITLE
Host/port being added to relative URLs in 1.8.0?

### ISSUE THREAD

**Issue by rdlugosz** [teampoltergeist/poltergeist#704]
I may have found a regression in the update from `1.7.0` to `1.8.0`. When using with Capybara, Poltergeist 1.7.0 and 1.8.0 return different values for the call `find_link("my link")[:href]` when `my link` is a relative URL (meaning it declares no host/port; it's just a path).

Given a basic CMS type of application, see the following spec (this tests some javascript that causes links external to the application to open in a new tab):
```ruby
it "makes all external open in a new window", js: true, focus: true do
  @blog_post = FactoryGirl.create(:article, body: <<-EOF)
    <p>This is an <a href="/foo">internal link</a></p>
    <p>This is an <a href="/foo#bar">internal anchor link</a></p>
    <p>This is an <a href="https://example.com/omgbbq">external link</a></p>
    EOF

  visit article_path(@blog_post)
  expect(find_link("internal link")[:href]).to    eq "/foo" # This line illustrates the problem
  expect(find_link("internal link")[:target]).to  eq("_self")
  expect(find_link("internal anchor link")[:href]).to    eq "/foo#bar"
  expect(find_link("internal anchor link")[:target]).to  eq("_self")
  expect(find_link("external link")[:href]).to    eq "https://example.com/omgbbq"
  expect(find_link("external link")[:target]).to  eq("_blank")
end
``` 

On pre-`1.8.0` versions of Poltergeist, all expectations pass. On version `1.8.0`, the expectations involving the links with relative urls fail with the following:

```
Failures:

  1) Articles (a.k.a. blog posts) post details makes all external open in a new window
     Failure/Error: expect(find_link("internal link")[:href]).to    eq "/foo"

       expected: "/foo"
            got: "http://127.0.0.1:59751/foo"

       (compared using ==)
     # ./spec/features/articles_spec.rb:49:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'
```

If I look at the page in Chrome dev tools there is no host/port added to the links... it seems like this is something that's only happening when run on Poltergeist 1.8. I've also verified that this does not happen when running without Poltergeist (though the checks for the proper `target` fail as you'd expect since the JS isn't being run).
