### ISSUE TITLE
Checking custom checkboxes

### ISSUE THREAD

**Issue by michaeldrotar** [teampoltergeist/poltergeist#741]
We were thinking of switching our project to use poltergeist, but many of our tests are now failing to work with our custom checkboxes.

We do the label-wrapped approach.. here's a simplified example:

```html
<label class="checkbox"><input type="checkbox">Label Text</label>
```

```css
.checkbox:before { /* custom checkbox visual */ }
.checkbox:checked:before { /* custom checkbox checked visual */ }
.checkbox input {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    border: 0;
}
```

The styles on the input are intended so that it's not technically hidden so that accessibility tools can still register it.. similar styles to what bootstrap uses for it's .sr-only class to do screen reader text.

Then our test uses the check method

```ruby
check 'Label Text'
```

I think the issue is around poltergeist determining the x/y coordinate of what to click on, then not seeing the element there? Is there anyway to fix this or an alternate approach we could take? We considered clicking the label and a couple other workarounds but that loses the functionality of not clicking if it's already checked and it's not as elegant as the `check` method.
